
//login action typesSET_REGISTER_ACCOUNT
export const SET_REGISTER_ACCOUNT = "SET_REGISTER_ACCOUNT";
export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST";
export const GET_SUBDEPARTMENT_LIST = "GET_SUBDEPARTMENT_LIST";
export const SET_UPDATE_WORKDEPARTMENT = "SET_UPDATE_WORKDEPARTMENT";
export const SET_UPDATE_AREATRAVEL = "SET_UPDATE_AREATRAVEL";
export const SET_UPDATE_ABILITY = "SET_UPDATE_ABILITY";
export const SET_NEW_POST = "SET_NEW_POST";
export const GET_POST_LIST = "GET_POST_LIST";
export const GET_COMMENT_LIST = "GET_COMMENT_LIST";
export const SET_COMMENT_POST = "SET_COMMENT_POST";
export const GET_POSTDETAIL_LIST = "GET_POSTDETAIL_LIST";

export const SET_SEND_MESSAGE = "SET_SEND_MESSAGE";
export const GET_MESSAGE_LIST = "GET_MESSAGE_LIST";
export const SET_LIKE_UNLIKE_POST = "SET_LIKE_UNLIKE_POST";
export const GET_PROFILE_LIST = "GET_PROFILE_LIST";
 export const SET_UPDATE_PROFILE = "SET_UPDATE_PROFILE";
export const SET_UPDATE_BACKGROUND = "SET_UPDATE_BACKGROUND";
export const SET_UPDATE_ABOUT = "SET_UPDATE_ABOUT";
export const GET_DELETE_POST = "GET_DELETE_POST";
export const SET_NETWORK_CRU = "SET_NETWORK_CRU";

export const GET_CRU_LIST = "GET_CRU_LIST";
export const GET_NETWORK_LIST = "GET_NETWORK_LIST";
export const GET_EVENT_CATEGORY = "GET_EVENT_CATEGORY";
export const GET_EVENT_LIST = "GET_EVENT_LIST";
 export const GET_EVENTDETAIL_LIST = "GET_EVENTDETAIL_LIST";
export const GET_NOTIFICATION_LIST = "GET_NOTIFICATION_LIST";
export const SET_PROJECT_ADD = "SET_PROJECT_ADD";
export const GET_PRODUCTION_LIST = "GET_PRODUCTION_LIST";
export const GET_MYPROJECT_LIST = "GET_MYPROJECT_LIST";
export const GET_PROJECTDETAIL_LIST = "GET_PROJECTDETAIL_LIST";
export const GET_LIKE_LIST = "GET_LIKE_LIST";
 export const SET_INVITE_CRU_PROJECT = "SET_INVITE_CRU_PROJECT";
export const GET_MESSAGEDETAIL_LIST = "GET_MESSAGEDETAIL_LIST";
export const SET_ACCEPT_USER = "SET_ACCEPT_USER";
export const GET_DELETE_USEREQUEST = "GET_DELETE_USEREQUEST";
export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const SET_APPLY_PROJECT = "SET_APPLY_PROJECT";
// export const SET_PARKING_LIST_LOADER = "SET_PARKING_LIST_LOADER";
// export const SET_NOTIFICATION_LOADER = "SET_NOTIFICATION_LOADER";

export const BUSINESS_LIST_DATA = "BUSINESS_LIST_DATA";
export const SET_OPENMESSAGE_DATA = "SET_OPENMESSAGE_DATA";
export const SET_LASTACTIVATED_SHIFT = "SET_LASTACTIVATED_SHIFT";
export const SET_PARKING_LIST_LOADER = "SET_PARKING_LIST_LOADER";
export const SET_NOTIFICATION_LOADER = "SET_NOTIFICATION_LOADER";

export const SET_TIMEOFFSCH_LOADER = "SET_TIMEOFFSCH_LOADER";


export const SET_MESSAGE_LOADER = "SET_MESSAGE_LOADER";
export const SET_LOGS_LOADER = "SET_LOGS_LOADER";

export const SET_ALLNOTIFICATION = "SET_ALLNOTIFICATION";
export const SET_EMASSAGE = "SET_EMASSAGE";
export const SET_GETGROUPMESSAGE = "SET_GETGROUPMESSAGE";
export const SET_CREATETHREAD = "SET_CREATETHREAD";
export const SET_ADDREPORT = "SET_ADDREPORT";
export const SET_SELECTED_SHIFT_MAP_ID = "SET_SELECTED_SHIFT_MAP_ID";
export const SET_INSIDE_BOUNDRY = "SET_INSIDE_BOUNDRY";
export const SET_TIMEOFFSCH = "SET_TIMEOFFSCH";
export const SET_TIMEOFF = "SET_TIMEOFF";
export const SET_MONTHSCHEDULE = "SET_MONTHSCHEDULE";
export const SET_TICKETINFO = "SET_TICKETINFO";
export const SET_SUBTYPE = "SET_SUBTYPE";
export const SET_ADDTICKET = "SET_ADDTICKET";
export const SET_CLOCKED_IN = "SET_CLOCKED_IN";
export const SET_LOGOS = "SET_LOGOS";
export const SET_PARKING = "SET_PARKING";
export const SET_SELECTED_SHIFT = "SET_SELECTED_SHIFT";
export const SET_LOGIN_CREDENTIAL = "SET_LOGIN_CREDENTIAL";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_LOGIN_LOADER = "SHOW_LOGIN_LOADER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const CHANGE_REMBER_ME_LOGIN_CREDENTIALS = "CHANGE_REMBER_ME_LOGIN_CREDENTIALS";
export const SET_DEFAULT_AUTH_SCREEN = "SET_DEFAULT_AUTH_SCREEN";
export const SET_NETWORK_STATE = "SET_NETWORK_STATE";

//forget password/reset password
export const SET_FORGET_PASSWORD_LOADER = "SET_FORGET_PASSWORD_LOADER";
export const SET_RESET_PASSWORD_LOADER = "SET_RESET_PASSWORD_LOADER";
export const SET_FORGET_PASSWORD_SUCCESS = "SET_FORGET_PASSWORD_SUCCESS";
export const SET_RESET_PASSWORD_SUCCESS = "SET_RESET_PASSWORD_SUCCESS";

//registration action types
export const SET_REGISTRATION_LOADER = "SHOW_REGISTRATION_LOADER";
export const SET_REGISTRATION_ERROR = "SET_REGISTRATION_ERROR";
export const SIGNUP_CREDENTIALS = "SIGNUP_CREDENTIALS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const VENDOR_REQUEST_LOADER = "VENDOR_REQUEST_LOADER";
export const VENDOR_REQUESTED_INFO = "VENDOR_REQUESTED_INFO";

//OTP Verification 
export const SET_OTP_LOADER = "SET_OTP_LOADER";
export const OTP_VERIFIED = "OTP_VERIFIED";
export const OTP_RESEND_SUCCESS = "OTP_RESEND_SUCCESS";

//Vendor

export const SET_CLOCKIN = "SET_CLOCKIN";
export const SET_CLOCKOUT = "SET_CLOCKOUT";
export const SET_VENDOR_LOADER = "SET_VENDOR_LOADER";
export const VENDOR_ADDED_SUCCESS = "OTP_RESEND_SUCCESS";
export const VENDOR_ADDED_INFO = "VENDOR_ADDED_INFO";
export const SET_VENDOR_LIST = "SET_VENDOR_LIST";
export const SET_VENDOR_LIST_LOADER = "SET_VENDOR_LIST_LOADER";

export const VENDOR_UPDATE_LOADER = "VENDOR_UPDATE_LOADER";
export const VENDOR_UPDATED_INFO = "VENDOR_UPDATED_INFO";

export const SET_SINGLE_VENDOR_LOADER = "SET_SINGLE_VENDOR_LOADER";
export const SET_SINGLE_VENDOR_INFO = "SET_SINGLE_VENDOR_INFO";

export const ACCEPT_VENDOR_LOADER = "SET_SINGLE_VENDOR_LOADER";
export const ACCEPT_VENDOR_INFO = "ACCEPT_VENDOR_INFO";

export const SET_CREATE_STORE_LOADER = "SET_CREATE_STORE_LOADER";
export const SET_CREATE_STORE_INFO = "SET_CREATE_STORE_INFO";
export const SET_UTILITYBILL_LOADER = "SET_UTILITYBILL_LOADER";
export const SET_UTILITYBILL_INFO = "SET_UTILITYBILL_INFO";
export const SET_STOREIMAGE_LOADER = "SET_STOREIMAGE_LOADER";
export const SET_STOREIMAGE_INFO = "SET_STOREIMAGE_INFO";
export const SET_STORE_AUTOFILL_INFO = "SET_STORE_AUTOFILL_INFO";
export const SET_VENDOR_NOTIFICATION_INFO = "SET_VENDOR_NOTIFICATION_INFO";

export const SET_USER_ID_RESET_PASSWORD = "SET_USER_ID_RESET_PASSWORD";

export const SET_TRACK_EARNING_LOADER = "SET_TRACK_EARNING_LOADER";
export const SET_TRACK_EARNING_DATA = "SET_TRACK_EARNING_DATA";
export const SET_VERIFICAITON_STATUS = "SET_VERIFICAITON_STATUS";
export const SET_VERIFICAITON_STEPS = "SET_VERIFICAITON_STEPS";
export const SET_BUSINESS_EXISTANCES = "SET_BUSINESS_EXISTANCES";


// Search Category (Business Type)
export const SET_SEARCH_CATEGORY_LOADER = "SET_SEARCH_CATEGORY_LOADER";
export const SET_SEARCH_CATEGORY_RESULT = "SET_SEARCH_CATEGORY_RESULT";

//Coupons
export const CREATE_COUPONS_SUCCESS = "CREATE_COUPONS_SUCCESS";
export const CREATE_COUPONS_LOADER = "CREATE_COUPONS_LOADER";

export const COUPONS_LIST_LOADER = "COUPONS_LIST_LOADER";
export const SET_COUPONS_LIST = "SET_COUPONS_LIST";

export const REDEEMED_COUPONS_LOADER = "REDEEMED_COUPONS_LOADER";
export const SET_REDEEMED_COUPONS = "SET_REDEEMED_COUPONS";

export const REDEEMED_COUPONS_TRACKING_LOADER = "REDEEMED_COUPONS_TRACKING_LOADER";
export const SET_REDEEMED_TRACKING_COUPONS = "SET_REDEEMED_TRACKING_COUPONS";
export const SET_IS_STORE = "SET_IS_STORE";

export const SUBSCRIPTION_PLAN_DATA = "SUBSCRIPTION_PLAN_DATA";
export const SUBSCRIPTION_PLAN_DATA_LOADER = "SUBSCRIPTION_PLAN_DATA_LOADER";
export const SUBSCRIPTION_STATUS = "SUBSCRIPTION_STATUS";
export const SUBSCRIPTION_PURCHASED_DATA = "SUBSCRIPTION_PURCHASED_DATA";
export const SUBSCRIPTION_PURCHASED_LOADER = "SUBSCRIPTION_PURCHASED_LOADER";
export const SET_PLAN_SELECTED_FLAG = "SET_PLAN_SELECTED_FLAG";
export const SET_REMAING_COUPON_CREDIT = "SET_REMAING_COUPON_CREDIT";

export const SET_PAYMENT_PROCESS = "SET_REMAING_COUPON_CREDIT";
export const PAYMENT_PROCESS_LOADER = "PAYMENT_PROCESS_LOADER";

export const IS_SUBSCRIPTION_SELECTED = "IS_SUBSCRIPTION_SELECTED";

//Banks
export const GET_BANKS_LOADER = "GET_BANKS_LOADER";
export const GET_BANKS = "GET_BANKS";

export const ADD_NEW_BANK_ACCOUNT_LOADER = "ADD_NEW_BANK_ACCOUNT_LOADER";
export const ADDED_BANK_INFO = "ADDED_BANK_INFO";

export const BANK_ACCOUNT_LIST_LOADER = "BANK_ACCOUNT_LIST_LOADER";
export const BANK_ACCOUNT_LIST = "BANK_ACCOUNT_LIST";

export const UPDATED_BANK_ACCOUNT_INFO = "UPDATED_BANK_ACCOUNT_INFO";
export const UPDATE_BANK_ACCOUNT_LOADER = "UPDATE_BANK_ACCOUNT_LOADER";

export const EXIST_EMAIL_DATA = "EXIST_EMAIL_DATA";
export const SIGNUP_ROLE_SUCCESS = "SIGNUP_ROLE_SUCCESS";
export const USER_SHIFT = "USER_SHIFT";